FROM debian:bookworm-slim

# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends \
    openconnect openssl curl iproute2 iputils-ping procps \
 && rm -rf /var/lib/apt/lists/*
