#!/command/with-contenv bash

echo "[INFO] ocserv-exporter starting"
export PATH=/opt/ocserv/bin:$PATH
exec /opt/ocserv-exporter/ocserv-exporter --interval "${EXPORTER_INTERVAL:-30s}" --listen "${EXPORTER_BIND:-127.0.0.1:8000}"
